---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: bggapp-deploy
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-deploy
spec:
  replicas: 3
  selector:
    matchLabels: # specify pod labels to match for identification/ debugging
      app: bgg
      name: bggapp-po
  template: # pod template
    metadata:
      name: bggapp-po
      labels: # pod labels
        app: bgg
        name: bggapp-po
    spec:
      containers:
      - name: bggapp-container
        image: stackupiss/bgg-backend:v1
        imagePullPolicy: IfNotPresent
        env: # environment variables
        - name: BGG_DB_USER
          value: root
        - name: BGG_DB_HOST
          value: bggdb-svc.bggns.svc.cluster.local
        envFrom:
        - secretRef:
            name: bgg-secret
        ports:
        - name: bggapp-port
          containerPort: 3000
        livenessProbe:
          httpGet:
            path: /healthz
            port: bggapp-port
          periodSeconds: 30
          initialDelaySeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: bggapp-svc
  namespace: bggns
  labels:
    app: bgg
    name: bggapp-svc
spec:
  type: ClusterIP
  # type: NodePort
  # type: LoadBalancer
  selector:
    app: bgg
    name: bggapp-po
  ports:
  - name: bggapp-svc-port
    port: 5000
    targetPort: bggapp-port