---
apiVersion: v1
kind: Namespace
metadata:
  name: minins

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mini-cm
  namespace: minins
data:
  MINIO_CI_CD: "true"

---
apiVersion: v1
kind: Secret
metadata:
  name: mini-secret
  namespace: minins
type: Opaque
data:
  MINIO_ROOT_USER: cm9vdF91c2Vy # 'root_user' base-64 encoded
  MINIO_ROOT_PASSWORD: cm9vdF9wYXNzd29yZA== # 'root_password' base-64 encoded